# Generated by Django 4.0.4 on 2023-04-20 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phoneNum', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('note', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sellingPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(max_length=250)),
                ('supplierID', models.CharField(blank=True, max_length=100, null=True)),
                ('classification', models.CharField(max_length=20, null=True)),
                ('barcode', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('shipID', models.AutoField(primary_key=True, serialize=False)),
                ('trackingNo', models.CharField(max_length=30)),
                ('shipDate', models.DateField()),
                ('note', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierID', models.AutoField(primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phoneNum', models.CharField(max_length=15)),
                ('country', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.IntegerField()),
                ('note', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('orderDate', models.DateField()),
                ('orderPrice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.customer')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.item')),
                ('shipID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('stackID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('expirationDate', models.DateField()),
                ('inboundDate', models.DateField()),
                ('lowQuantity', models.IntegerField(default=1)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.item')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('recID', models.AutoField(primary_key=True, serialize=False)),
                ('shipmentDate', models.DateField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trackingNo', models.CharField(max_length=30)),
                ('note', models.CharField(max_length=300)),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.supplier')),
            ],
        ),
    ]
