# Generated by Django 4.0.4 on 2023-04-21 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Top_Customer',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('customerID', models.CharField(max_length=10)),
                ('totalOrders', models.IntegerField()),
                ('totalSpent', models.DecimalField(decimal_places=2, max_digits=11)),
                ('averageOrderPrice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
