# Generated by Django 4.0.4 on 2023-02-24 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_item_barcode_alter_customer_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storefront.shipment'),
        ),
    ]
