# Generated by Django 4.0.4 on 2023-04-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_alter_order_shipid'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='lowQuantity',
            field=models.IntegerField(default=1),
        ),
    ]
